services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/securePassword123
    restart: unless-stopped

  server:
    build: ./server
    depends_on:
      database:
        condition: service_healthy

  client:
    build: ./client
    depends_on:
      - server

  caddy:
    image: caddy:latest
    ports:
      - 8080:80
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - client
      - server
